version: '3.4'

services:
  mongo:
     image: mongo
     restart: always
     container_name: MongoDB_Container
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: example
     ports:
      - 27017:27017
     networks:
      - mongodb_backend_network
    
  #mongo-express:
  #   image: mongo-express
  #   restart: always
  #   container_name: Mongo__Express_Container
  #   ports:
  #    - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #   depends_on:
  #     - mongo
  #   networks:
  #    - mongodb_backend_network
  itemsapi_v1:
    image: ${DOCKER_REGISTRY-}itemsapiv1
    container_name: Items_API_Container
    build:
      context: .
      dockerfile: ItemsAPI_V1\Dockerfile
    ports:
      - 5000:80
    environment:
      MongoDB__Host: mongo
      MONGODB_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    depends_on:
      - mongo 
    networks:
      - mongodb_backend_network
networks:
    mongodb_backend_network:
      driver: nat
  
